
// This file was auto-generated by ML.NET Model Builder. 

using PricePredictionModel_Console;

// Create single instance of sample data from first line of dataset for model input
PricePredictionModel.ModelInput sampleData = new PricePredictionModel.ModelInput()
{
    CPU = @"i5",
    GHz = 2.5F,
    GPU = @"intel",
    RAM = 4F,
    RAMType = @"ddr3",
    Screen = 13.3F,
    Storage = 500F,
    SSD = false,
    Weight = 2F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");


Console.WriteLine($"CPU: {@"i5"}");
Console.WriteLine($"GHz: {2.5F}");
Console.WriteLine($"GPU: {@"intel"}");
Console.WriteLine($"RAM: {4F}");
Console.WriteLine($"RAMType: {@"ddr3"}");
Console.WriteLine($"Screen: {13.3F}");
Console.WriteLine($"Storage: {500F}");
Console.WriteLine($"SSD: {false}");
Console.WriteLine($"Weight: {2F}");
Console.WriteLine($"Price: {527F}");


var predictionResult = PricePredictionModel.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

